import path from 'node:path'
import { mkdir, readdir, stat, copyFile } from 'node:fs/promises'
import { NextResponse } from 'next/server'

type SyncResult = {
  ok: boolean
  copiedFiles: number
  skippedFiles: number
  errors: string[]
  fromDir: string
  toDir: string
}

async function ensureDir(p: string) {
  await mkdir(p, { recursive: true })
}

async function copyRecursive(
  fromDir: string,
  toDir: string,
  result: { copied: number; skipped: number; errors: string[] },
): Promise<void> {
  await ensureDir(toDir)
  const entries = await readdir(fromDir, { withFileTypes: true })
  for (const ent of entries) {
    const src = path.join(fromDir, ent.name)
    const dst = path.join(toDir, ent.name)
    if (ent.isDirectory()) {
      await copyRecursive(src, dst, result)
      continue
    }
    if (!ent.isFile()) continue

    // Only sync assets we serve directly.
    const lower = ent.name.toLowerCase()
    const isAsset =
      lower.endsWith('.png') || lower.endsWith('.json') || lower.endsWith('.zip') || lower.endsWith('.webp') || lower.endsWith('.gif')
    if (!isAsset) {
      result.skipped += 1
      continue
    }

    try {
      // Skip identical files quickly by size+mtime heuristic (safe enough for local sync).
      const [s1, s2] = await Promise.all([
        stat(src),
        stat(dst).catch(() => null),
      ])
      if (s2 && s1.size === s2.size && s1.mtimeMs <= s2.mtimeMs) {
        result.skipped += 1
        continue
      }
      await ensureDir(path.dirname(dst))
      await copyFile(src, dst)
      result.copied += 1
    } catch (e) {
      result.errors.push(`${ent.name}: ${e instanceof Error ? e.message : String(e)}`)
    }
  }
}

/**
 * Sync PixelLab assets generated by ai-rpg-poc into battle-poc public folder.
 *
 * Copies the entire characters folder from:
 *   ai-rpg-poc/examples/demo-project/assets/characters/
 * Into:
 *   battle-poc/public/assets/characters/
 */
export async function POST() {
  try {
    const repoRoot = path.resolve(process.cwd(), '..')
    const fromDir = path.join(repoRoot, 'ai-rpg-poc', 'examples', 'demo-project', 'assets', 'characters')
    const toDir = path.join(process.cwd(), 'public', 'assets', 'characters')

    const result = { copied: 0, skipped: 0, errors: [] as string[] }
    await copyRecursive(fromDir, toDir, result)

    const payload: SyncResult = {
      ok: result.errors.length === 0,
      copiedFiles: result.copied,
      skippedFiles: result.skipped,
      errors: result.errors,
      fromDir,
      toDir,
    }
    return NextResponse.json(payload, { status: payload.ok ? 200 : 207 })
  } catch (e) {
    return NextResponse.json(
      {
        ok: false,
        copiedFiles: 0,
        skippedFiles: 0,
        errors: [e instanceof Error ? e.message : String(e)],
      },
      { status: 500 },
    )
  }
}

